---
title: "Homework Template"
output:
  html_document: default
  pdf_document: default
date: "2023-10-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tinytex)
library(ggplot2)
library(palmerpenguins)
library(janitor)
library(dplyr)
library(tidyverse)
library(png)
```

## QUESTION 2: Data Pipeline

------------------------------------------------------------------------

### Introduction

I am going to investigate whether there is a significant relationship between body mass and flipper length for adelie penguins. I am going to clean the data, plot a clear graph of this data and then move on to perform a pearsons correlation test to see if it is significant. 

The first chunk of code cleans the data, and plots a graph.

```{r Data Exploration}
#so here, I source my file with the preset cleaning functions
source("REPRODUCIBLE_FIGURES/cleaningfunctions/cleaning.R") 
#and then load the data
data("penguins")

#this pipeline cleans my data, removing NA values, and filtering by the species I focus on
penguins_clean <- penguins%>%
  remove_NA() %>%
clean_column_names() %>%
filter_by_species("Adelie") 

#checking the data
head(penguins_clean)

#time to make a figure
goodscatter<- ggplot(penguins_clean, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(size = 2, alpha = 0.5) + 
  labs(title = "Correlation between Flipper Length and Body Mass in Adelie Penguins ", 
       x = "Flipper Length", 
       y = "Body Mass") 


goodscatter

# Save the plot to the subfolder
ggsave(filename = paste0("REPRODUCIBLE_FIGURES/plots", "/goodscatter.pdf"), plot = goodscatter)
```

### Hypothesis

Here I am testing whether there is a correlation between the variables. Ill use a pearson correlation coefficient and a hypothesis test. 
- Null Hypothesis - the observed correlation is NOT significantly different from zero
- Alternative Hypothesis - the observed correlation IS significantly different from zero

This chunk of code runs the simple test.


### Statistical Methods

```{r Statistics}
#Pearson correlation coefficient
correlation<- cor.test(penguins_clean$flipper_length, penguins_clean$body_mass)

print(correlation)
```

### Results & Discussion

Here, the correlation is shown to be 0.4648539, which is positive. The p value is hugely lower than 0.05, our chosen significance level, so we can safely reject the null hypothesis and conclude that there is a significant positive correlation between the two variables.

```{r Plotting Results}

#here I plot my graph again, including a regression line
regressionscatter<- ggplot(penguins_clean, aes(x = flipper_length, y = body_mass)) +
  geom_point(size = 2, alpha = 0.5) + 
  labs(title = "Correlation between Flipper Length and Body Mass in Adelie Penguins ", 
       x = "Flipper Length", 
       y = "Body Mass")  +
  geom_smooth(method = "lm")

```

### Conclusion

Therefore, I can conclude that For Adelie penguins, as they grow heavier, they also are more likely to have longer flippers.

------------------------------------------------------------------------
